"""Constants for Tesla AI."""

DOMAIN = "pom_tesla_report"
DEFAULT_NAME = "Tesla AI"

TRIP_STATE_KEY = "trip_state"
MANUAL_TRACKING_STATE_KEY = "manual_tracking_state"

DATA_ASYNC_START_MANUAL_TRACKING = "async_start_manual_tracking"
DATA_ASYNC_FINISH_MANUAL_TRACKING = "async_finish_manual_tracking"

CONF_NAME = "name"

CONF_SHIFT_STATE_ENTITY = "shift_state_entity"
CONF_SPEED_ENTITY = "speed_entity"
CONF_ODOMETER_ENTITY = "odometer_entity"
CONF_BATTERY_LEVEL_ENTITY = "battery_level_entity"
CONF_ENERGY_REMAINING_ENTITY = "energy_remaining_entity"
CONF_ELEVATION_ENTITY = "elevation_entity"
CONF_CLIMATE_ENTITY = "climate_entity"

CONF_CHARGING_ENTITY = "charging_entity"
CONF_CHARGE_ENERGY_ADDED_ENTITY = "charge_energy_added_entity"

CONF_SUPERCHARGER_PRICE = "supercharger_price"
CONF_ZES_PRICE = "zes_price"
CONF_ASTOR_PRICE = "astor_price"
CONF_CHARGE_PROVIDER_PRESETS = "charge_provider_presets"
CONF_CHARGING_REPORT_MODE = "charging_report_mode"

CHARGING_REPORT_MODE_DIRECT = "direct"
CHARGING_REPORT_MODE_PROMPT = "prompt"
DEFAULT_CHARGING_REPORT_MODE = CHARGING_REPORT_MODE_PROMPT

CONF_APP_LANGUAGE = "app_language"
APP_LANGUAGE_TR = "tr"
APP_LANGUAGE_EN = "en"
DEFAULT_APP_LANGUAGE = APP_LANGUAGE_TR

# Legacy report-language key kept for backward compatibility; new code follows CONF_APP_LANGUAGE.
CONF_REPORT_LANGUAGE = "report_language"
DEFAULT_REPORT_LANGUAGE = DEFAULT_APP_LANGUAGE

CONF_REPORT_CURRENCY = "report_currency"
DEFAULT_REPORT_CURRENCY = "TL"
REPORT_CURRENCY_OPTIONS = ["TL", "EUR", "USD", "GBP", "CHF", "CAD", "AUD", "JPY", "NOK", "SEK", "DKK", "PLN", "CZK", "HUF", "RON"]

CONF_AI_TELEGRAM_REPORT_LANGUAGE = "ai_telegram_report_language"
AI_TELEGRAM_REPORT_LANGUAGE_AUTO = "auto"
AI_TELEGRAM_REPORT_LANGUAGE_TR = "tr"
AI_TELEGRAM_REPORT_LANGUAGE_EN = "en"
DEFAULT_AI_TELEGRAM_REPORT_LANGUAGE = AI_TELEGRAM_REPORT_LANGUAGE_AUTO

TRIP_MONTHLY_LEDGER_FILENAME = "pom_trip_monthly_ledger.json"

CONF_TELEGRAM_TARGET = "telegram_target"
CONF_BUILTIN_TELEGRAM_ENABLED = "builtin_telegram_enabled"
CONF_BUILTIN_TELEGRAM_BOT_TOKEN = "builtin_telegram_bot_token"
CONF_BUILTIN_TELEGRAM_POLL_ENABLED = "builtin_telegram_poll_enabled"
CONF_BUILTIN_TELEGRAM_POLL_INTERVAL_SECONDS = "builtin_telegram_poll_interval_seconds"

CONF_AUTO_TRIP_TRACKING = "auto_trip_tracking"
CONF_AUTO_START_SPEED_THRESHOLD = "auto_start_speed_threshold"

DEFAULT_SUPERCHARGER_PRICE = 9.90
DEFAULT_ZES_PRICE = 16.49
DEFAULT_ASTOR_PRICE = 12.49
DEFAULT_CHARGE_PROVIDER_PRESETS = [
    {"name": "Supercharger", "unit_price": DEFAULT_SUPERCHARGER_PRICE, "currency": DEFAULT_REPORT_CURRENCY},
    {"name": "ZES", "unit_price": DEFAULT_ZES_PRICE, "currency": DEFAULT_REPORT_CURRENCY},
    {"name": "Astor", "unit_price": DEFAULT_ASTOR_PRICE, "currency": DEFAULT_REPORT_CURRENCY},
]
CHARGE_COST_LEDGER_FILENAME = f"{DOMAIN}_charge_cost_ledger.json"
CHARGE_COST_MONTHLY_REPORT_HOUR = 23
CHARGE_COST_MONTHLY_REPORT_MINUTE = 55

PERIODIC_REPORT_STATE_FILENAME = f"{DOMAIN}_periodic_report_state.json"
CONF_TELEGRAM_WEEKLY_TRIP_REPORT_ENABLED = "telegram_weekly_trip_report_enabled"
CONF_TELEGRAM_MONTHLY_TRIP_REPORT_ENABLED = "telegram_monthly_trip_report_enabled"
CONF_TELEGRAM_WEEKLY_CHARGE_REPORT_ENABLED = "telegram_weekly_charge_report_enabled"
CONF_TELEGRAM_MONTHLY_CHARGE_REPORT_ENABLED = "telegram_monthly_charge_report_enabled"
DEFAULT_TELEGRAM_WEEKLY_TRIP_REPORT_ENABLED = False
DEFAULT_TELEGRAM_MONTHLY_TRIP_REPORT_ENABLED = False
DEFAULT_TELEGRAM_WEEKLY_CHARGE_REPORT_ENABLED = False
DEFAULT_TELEGRAM_MONTHLY_CHARGE_REPORT_ENABLED = False
PERIODIC_REPORT_WEEKDAY = 6  # Sunday, datetime.weekday(): Monday=0
PERIODIC_REPORT_HOUR = 23
PERIODIC_REPORT_MINUTE = 55

DEFAULT_AUTO_TRIP_TRACKING = True
DEFAULT_AUTO_START_SPEED_THRESHOLD = 2.0
DEFAULT_BUILTIN_TELEGRAM_ENABLED = True
DEFAULT_BUILTIN_TELEGRAM_POLL_ENABLED = False
DEFAULT_BUILTIN_TELEGRAM_POLL_INTERVAL_SECONDS = 3

CONF_LIVE_TRIP_ENABLED = "live_trip_enabled"
CONF_LIVE_TRIP_UPDATE_INTERVAL_SECONDS = "live_trip_update_interval_seconds"
CONF_LIVE_TRIP_TRAFFIC_SPEED_THRESHOLD = "live_trip_traffic_speed_threshold"
CONF_LIVE_TRIP_FINISH_DELAY_SECONDS = "live_trip_finish_delay_seconds"
CONF_LIVE_TRIP_MIN_DISTANCE_KM = "live_trip_min_distance_km"
CONF_LIVE_TRIP_IGNORE_SHORT_MANEUVERS = "live_trip_ignore_short_maneuvers"
CONF_LIVE_TRIP_CANDIDATE_MIN_DISTANCE_KM = "live_trip_candidate_min_distance_km"
CONF_LIVE_TRIP_CANDIDATE_MIN_DURATION_SECONDS = "live_trip_candidate_min_duration_seconds"
CONF_LIVE_TRIP_AI_SEGMENT_DISTANCE_KM = "live_trip_ai_segment_distance_km"

DEFAULT_LIVE_TRIP_ENABLED = True
DEFAULT_LIVE_TRIP_UPDATE_INTERVAL_SECONDS = 5
DEFAULT_LIVE_TRIP_TRAFFIC_SPEED_THRESHOLD = 20.0
DEFAULT_LIVE_TRIP_FINISH_DELAY_SECONDS = 1800
DEFAULT_LIVE_TRIP_MIN_DISTANCE_KM = 0.0
DEFAULT_LIVE_TRIP_IGNORE_SHORT_MANEUVERS = True
DEFAULT_LIVE_TRIP_CANDIDATE_MIN_DISTANCE_KM = 0.30
DEFAULT_LIVE_TRIP_CANDIDATE_MIN_DURATION_SECONDS = 120
DEFAULT_LIVE_TRIP_AI_SEGMENT_DISTANCE_KM = 10.0
LIVE_TRIP_AI_SEGMENT_DISTANCE_OPTIONS = (1.0, 5.0, 10.0)

CONF_SHOW_DISTANCE = "show_distance"
CONF_SHOW_DURATION = "show_duration"
CONF_SHOW_TRAFFIC = "show_traffic"
CONF_SHOW_AVERAGE_SPEED = "show_average_speed"
CONF_SHOW_ENERGY = "show_energy"
CONF_SHOW_CONSUMPTION = "show_consumption"
CONF_SHOW_BATTERY = "show_battery"
CONF_SHOW_COST = "show_cost"
CONF_SHOW_CLIMATE = "show_climate"
CONF_SHOW_ELEVATION = "show_elevation"
CONF_SHOW_TRIP_MAP = "show_trip_map"

DEFAULT_SHOW_DISTANCE = True
DEFAULT_SHOW_DURATION = True
DEFAULT_SHOW_TRAFFIC = True
DEFAULT_SHOW_AVERAGE_SPEED = True
DEFAULT_SHOW_ENERGY = True
DEFAULT_SHOW_CONSUMPTION = True
DEFAULT_SHOW_BATTERY = True
DEFAULT_SHOW_COST = True
DEFAULT_SHOW_CLIMATE = True
DEFAULT_SHOW_ELEVATION = True
DEFAULT_SHOW_TRIP_MAP = True


CONF_AI_ENABLED = "ai_enabled"
CONF_OPENAI_API_KEY = "openai_api_key"
CONF_OPENAI_MODEL = "openai_model"
CONF_AI_TELEGRAM_TARGET = "ai_telegram_target"
CONF_AI_NAME = "ai_name"
CONF_AI_USER_ADDRESS = "ai_user_address"
CONF_AI_SYSTEM_PROMPT = "ai_system_prompt"
CONF_AI_MAX_OUTPUT_TOKENS = "ai_max_output_tokens"

DEFAULT_AI_ENABLED = True
DEFAULT_OPENAI_MODEL = "gpt-4.1-mini"
DEFAULT_AI_NAME = "Tesla AI"
DEFAULT_AI_USER_ADDRESS = ""
DEFAULT_AI_MAX_OUTPUT_TOKENS = 700
DEFAULT_AI_SYSTEM_PROMPT = """Sen POM AI adında, kullanıcının Tesla ve Home Assistant rapor asistanısın.
Her zaman Türkçe cevap ver.
Kısa, net ve kendinden emin konuş.
Sana verilen Home Assistant ve Tesla verilerini esas al.
Veri yoksa uydurma; hangi verinin eksik olduğunu söyle.
Bu sürümde sadece bilgi ver ve yorum yap.
Home Assistant servisi çalıştırma, aracı kontrol etme, kapı/kilit/klima/frunk/trunk/window gibi riskli komutları uygulama.
Kullanıcı senden işlem yapmanı isterse bunun bu sürümde sadece bilgi amaçlı olduğunu söyle."""

CONF_AI_TELEGRAM_LISTENER_ENABLED = "ai_telegram_listener_enabled"
CONF_AI_TELEGRAM_LISTENER_CHAT_ID = "ai_telegram_listener_chat_id"
CONF_AI_TELEGRAM_ALLOWED_USER_ID = "ai_telegram_allowed_user_id"
CONF_AI_TELEGRAM_PREFIX = "ai_telegram_prefix"
CONF_AI_TELEGRAM_INCLUDE_CONTEXT = "ai_telegram_include_context"
CONF_AI_CONFIRM_OPTIONAL_CONTROLS = "ai_confirm_optional_controls"

DEFAULT_AI_TELEGRAM_LISTENER_ENABLED = True
DEFAULT_AI_TELEGRAM_ALLOWED_USER_ID = ""
DEFAULT_AI_TELEGRAM_PREFIX = "POM"
DEFAULT_AI_TELEGRAM_INCLUDE_CONTEXT = True
DEFAULT_AI_CONFIRM_OPTIONAL_CONTROLS = True


CONF_TRIP_MAP_ENABLED = "trip_map_enabled"
CONF_TRIP_MAP_TRACKER_ENTITY = "trip_map_tracker_entity"
CONF_TRIP_MAP_SAMPLE_INTERVAL_SECONDS = "trip_map_sample_interval_seconds"
CONF_TRIP_MAP_MIN_MOVEMENT_METERS = "trip_map_min_movement_meters"
CONF_TRIP_MAP_SEND_SEPARATE_PNG = "trip_map_send_separate_png"

DEFAULT_TRIP_MAP_ENABLED = True
DEFAULT_TRIP_MAP_TRACKER_ENTITY = ""
DEFAULT_TRIP_MAP_SAMPLE_INTERVAL_SECONDS = 5
DEFAULT_TRIP_MAP_MIN_MOVEMENT_METERS = 15.0
DEFAULT_TRIP_MAP_SEND_SEPARATE_PNG = True


CONF_AI_PERSONALITY = "ai_personality"
CONF_AI_ANSWER_LENGTH = "ai_answer_length"
CONF_AI_CONTEXT_MODE = "ai_context_mode"
CONF_AI_MAIN_TESLA_ENTITY = "ai_main_tesla_entity"
CONF_AI_AUTO_DISCOVER_DEVICE_ENTITIES = "ai_auto_discover_device_entities"
CONF_AI_INCLUDE_UNAVAILABLE = "ai_include_unavailable"
CONF_AI_MAX_CONTEXT_ENTITIES = "ai_max_context_entities"
CONF_AI_EXTRA_CONTEXT_ENTITIES = "ai_extra_context_entities"
CONF_AI_EXCLUDED_CONTEXT_ENTITIES = "ai_excluded_context_entities"

CONF_REVERSE_GEOCODING_ENABLED = "reverse_geocoding_enabled"
CONF_REVERSE_GEOCODING_CACHE_MINUTES = "reverse_geocoding_cache_minutes"
CONF_REVERSE_GEOCODING_USE_IN_AI = "reverse_geocoding_use_in_ai"

DEFAULT_REVERSE_GEOCODING_ENABLED = True
DEFAULT_REVERSE_GEOCODING_CACHE_MINUTES = 5
DEFAULT_REVERSE_GEOCODING_USE_IN_AI = True

AI_PERSONALITY_PROFESSIONAL = "professional"
AI_PERSONALITY_FRIENDLY = "friendly"
AI_PERSONALITY_FUNNY = "funny"
AI_PERSONALITY_SHORT_DIRECT = "short_direct"
AI_PERSONALITY_PREMIUM = "premium_tesla_assistant"
AI_PERSONALITY_TURKISH_BUDDY = "turkish_buddy"
AI_PERSONALITY_LAZ_BLACK_SEA = "laz_black_sea"

AI_ANSWER_LENGTH_SHORT = "short"
AI_ANSWER_LENGTH_NORMAL = "normal"
AI_ANSWER_LENGTH_DETAILED = "detailed"

AI_CONTEXT_MODE_BASIC = "basic"
AI_CONTEXT_MODE_SMART_AUTO = "smart_auto"
AI_CONTEXT_MODE_SELECTED_DEVICE = "selected_device"
AI_CONTEXT_MODE_SMART_MANUAL = "smart_manual"
AI_CONTEXT_MODE_MANUAL_ONLY = "manual_only"

DEFAULT_AI_PERSONALITY = AI_PERSONALITY_FRIENDLY
DEFAULT_AI_ANSWER_LENGTH = AI_ANSWER_LENGTH_SHORT
DEFAULT_AI_CONTEXT_MODE = AI_CONTEXT_MODE_SMART_MANUAL
DEFAULT_AI_MAIN_TESLA_ENTITY = ""
DEFAULT_AI_AUTO_DISCOVER_DEVICE_ENTITIES = True
DEFAULT_AI_INCLUDE_UNAVAILABLE = True
DEFAULT_AI_MAX_CONTEXT_ENTITIES = 60
DEFAULT_AI_EXTRA_CONTEXT_ENTITIES = []
DEFAULT_AI_EXCLUDED_CONTEXT_ENTITIES = []


CONF_AI_ALERTS_ENABLED = "ai_alerts_enabled"
CONF_AI_ALERT_STYLE = "ai_alert_style"
CONF_AI_ALERT_COOLDOWN_MINUTES = "ai_alert_cooldown_minutes"
CONF_AI_ALERT_LOW_BATTERY_ENABLED = "ai_alert_low_battery_enabled"
CONF_AI_ALERT_LOW_BATTERY_THRESHOLD = "ai_alert_low_battery_threshold"
CONF_AI_ALERT_POST_TRIP_SUMMARY_ENABLED = "ai_alert_post_trip_summary_enabled"
CONF_AI_TRIP_STORY_DETAIL_LEVEL = "ai_trip_story_detail_level"
AI_TRIP_STORY_DETAIL_BASIC = "basic"
AI_TRIP_STORY_DETAIL_BALANCED = "balanced"
AI_TRIP_STORY_DETAIL_DETAILED = "detailed"
DEFAULT_AI_TRIP_STORY_DETAIL_LEVEL = AI_TRIP_STORY_DETAIL_DETAILED
AI_TRIP_STORY_DETAIL_OPTIONS = [AI_TRIP_STORY_DETAIL_BASIC, AI_TRIP_STORY_DETAIL_BALANCED, AI_TRIP_STORY_DETAIL_DETAILED]
CONF_AI_ALERT_CHARGE_FINISHED_ENABLED = "ai_alert_charge_finished_enabled"
CONF_AI_ALERT_CHARGING_STOPPED_ENABLED = "ai_alert_charging_stopped_enabled"
CONF_AI_ALERT_TIRE_PRESSURE_ENABLED = "ai_alert_tire_pressure_enabled"
CONF_AI_ALERT_TIRE_PRESSURE_THRESHOLD_BAR = "ai_alert_tire_pressure_threshold_bar"
CONF_AI_ALERT_HIGH_BATTERY_TEMP_ENABLED = "ai_alert_high_battery_temp_enabled"
CONF_AI_ALERT_HIGH_BATTERY_TEMP_THRESHOLD_C = "ai_alert_high_battery_temp_threshold_c"
CONF_AI_ALERT_CLIMATE_LEFT_ON_ENABLED = "ai_alert_climate_left_on_enabled"
CONF_AI_ALERT_CLIMATE_LEFT_ON_DELAY_MINUTES = "ai_alert_climate_left_on_delay_minutes"
CONF_AI_ALERT_UNLOCKED_ENABLED = "ai_alert_unlocked_enabled"
CONF_AI_ALERT_UNLOCKED_DELAY_MINUTES = "ai_alert_unlocked_delay_minutes"
CONF_AI_ALERT_DOOR_WINDOW_OPEN_ENABLED = "ai_alert_door_window_open_enabled"
CONF_AI_ALERT_DOOR_WINDOW_OPEN_DELAY_MINUTES = "ai_alert_door_window_open_delay_minutes"
CONF_AI_ALERT_WINDOW_OPEN_INSTANT_ENABLED = "ai_alert_window_open_instant_enabled"

AI_ALERT_STYLE_RULE = "rule"
AI_ALERT_STYLE_AI = "ai"

DEFAULT_AI_ALERTS_ENABLED = False
DEFAULT_AI_ALERT_STYLE = AI_ALERT_STYLE_AI
DEFAULT_AI_ALERT_COOLDOWN_MINUTES = 30
DEFAULT_AI_ALERT_LOW_BATTERY_ENABLED = True
DEFAULT_AI_ALERT_LOW_BATTERY_THRESHOLD = 20
DEFAULT_AI_ALERT_POST_TRIP_SUMMARY_ENABLED = True
DEFAULT_AI_ALERT_CHARGE_FINISHED_ENABLED = True
DEFAULT_AI_ALERT_CHARGING_STOPPED_ENABLED = True
DEFAULT_AI_ALERT_TIRE_PRESSURE_ENABLED = True
DEFAULT_AI_ALERT_TIRE_PRESSURE_THRESHOLD_BAR = 36.0
DEFAULT_AI_ALERT_HIGH_BATTERY_TEMP_ENABLED = True
DEFAULT_AI_ALERT_HIGH_BATTERY_TEMP_THRESHOLD_C = 55
DEFAULT_AI_ALERT_CLIMATE_LEFT_ON_ENABLED = False
DEFAULT_AI_ALERT_CLIMATE_LEFT_ON_DELAY_MINUTES = 10
DEFAULT_AI_ALERT_UNLOCKED_ENABLED = True
DEFAULT_AI_ALERT_UNLOCKED_DELAY_MINUTES = 2
DEFAULT_AI_ALERT_DOOR_WINDOW_OPEN_ENABLED = True
DEFAULT_AI_ALERT_DOOR_WINDOW_OPEN_DELAY_MINUTES = 5
DEFAULT_AI_ALERT_WINDOW_OPEN_INSTANT_ENABLED = False


CONF_VEHICLE_ENTITY_MAP = "vehicle_entity_map"
DEFAULT_VEHICLE_ENTITY_MAP = []
CONF_PANEL_REPORT_ENTITY_MAP = "panel_report_entity_map"
DEFAULT_PANEL_REPORT_ENTITY_MAP = []
CONF_PANEL_AI_ENTITY_MAP = "panel_ai_entity_map"
DEFAULT_PANEL_AI_ENTITY_MAP = []
CONF_PANEL_DASHBOARD_ENTITY_MAP = "panel_dashboard_entity_map"
DEFAULT_PANEL_DASHBOARD_ENTITY_MAP = []

VEHICLE_ROLE_BATTERY_LEVEL = "battery_level"
VEHICLE_ROLE_BATTERY_RANGE = "battery_range"
VEHICLE_ROLE_ENERGY_REMAINING = "energy_remaining"
VEHICLE_ROLE_CHARGING_STATE = "charging_state"
VEHICLE_ROLE_CHARGE_ENERGY_ADDED = "charge_energy_added"
VEHICLE_ROLE_CHARGER_POWER = "charger_power"
VEHICLE_ROLE_SPEED = "speed"
VEHICLE_ROLE_SHIFT_STATE = "shift_state"
VEHICLE_ROLE_ODOMETER = "odometer"
VEHICLE_ROLE_ELEVATION = "elevation"
VEHICLE_ROLE_CLIMATE = "climate"
VEHICLE_ROLE_INSIDE_TEMPERATURE = "inside_temperature"
VEHICLE_ROLE_OUTSIDE_TEMPERATURE = "outside_temperature"
VEHICLE_ROLE_BATTERY_TEMPERATURE = "battery_temperature"
VEHICLE_ROLE_TIRE_PRESSURE_FRONT_LEFT = "tire_pressure_front_left"
VEHICLE_ROLE_TIRE_PRESSURE_FRONT_RIGHT = "tire_pressure_front_right"
VEHICLE_ROLE_TIRE_PRESSURE_REAR_LEFT = "tire_pressure_rear_left"
VEHICLE_ROLE_TIRE_PRESSURE_REAR_RIGHT = "tire_pressure_rear_right"
VEHICLE_ROLE_DOOR_WINDOW = "door_window"
VEHICLE_ROLE_LOCK_STATE = "lock_state"
VEHICLE_ROLE_LOCATION_TRACKER = "location_tracker"
VEHICLE_ROLE_VEHICLE_STATE = "vehicle_state"
VEHICLE_ROLE_USER_PRESENT = "user_present"
VEHICLE_ROLE_OTHER = "other"

VEHICLE_ENTITY_ROLES = [
    VEHICLE_ROLE_BATTERY_LEVEL,
    VEHICLE_ROLE_BATTERY_RANGE,
    VEHICLE_ROLE_ENERGY_REMAINING,
    VEHICLE_ROLE_CHARGING_STATE,
    VEHICLE_ROLE_CHARGE_ENERGY_ADDED,
    VEHICLE_ROLE_CHARGER_POWER,
    VEHICLE_ROLE_SPEED,
    VEHICLE_ROLE_SHIFT_STATE,
    VEHICLE_ROLE_ODOMETER,
    VEHICLE_ROLE_ELEVATION,
    VEHICLE_ROLE_CLIMATE,
    VEHICLE_ROLE_INSIDE_TEMPERATURE,
    VEHICLE_ROLE_OUTSIDE_TEMPERATURE,
    VEHICLE_ROLE_BATTERY_TEMPERATURE,
    VEHICLE_ROLE_TIRE_PRESSURE_FRONT_LEFT,
    VEHICLE_ROLE_TIRE_PRESSURE_FRONT_RIGHT,
    VEHICLE_ROLE_TIRE_PRESSURE_REAR_LEFT,
    VEHICLE_ROLE_TIRE_PRESSURE_REAR_RIGHT,
    VEHICLE_ROLE_DOOR_WINDOW,
    VEHICLE_ROLE_LOCK_STATE,
    VEHICLE_ROLE_LOCATION_TRACKER,
    VEHICLE_ROLE_VEHICLE_STATE,
    VEHICLE_ROLE_USER_PRESENT,
    VEHICLE_ROLE_OTHER,
]
